apiVersion: v2
name: homepage
description: A Helm chart for the Next.js homepage.
type: application
version: 0.1.0
appVersion: 1.0.0
icon: https://raw.githubusercontent.com/spitikos/spitikos/main/icon.svg
annotations:
  charts.helm.sh/display-name: "Homepage"

dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../_common"
