apiVersion: v2
name: prometheus-wrapper
description: A wrapper chart for deploying the kube-prometheus stack.
type: application
version: 0.1.0
appVersion: v0.83.0
icon: "https://raw.githubusercontent.com/spitikos/spitikos/main/icon.svg"
annotations:
  charts.helm.sh/display-name: Prometheus

dependencies:
  - name: kube-prometheus-stack
    version: 75.18.1
    repository: "https://prometheus-community.github.io/helm-charts"
